name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  coverage:
    name: "Coverage"
    runs-on: ubuntu-latest
    needs: [main]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: ./coverage
          merge-multiple: true

      - name: Upload report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  main:
    name: "Main"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Coverage
        run: npm run coverage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-main
          path: coverage/
